version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pnpm"
    directory: "/hapax-logos"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pnpm"
    directory: "/vscode"
    schedule:
      interval: "weekly"
