import { ItemView, WorkspaceLeaf } from "obsidian";
import type { NoteContext } from "./types";
import { NoteKind } from "./types";
import type { LogosClient } from "./logos-client";
import {
  renderSprintStatus,
  renderStimmungBadge,
  renderStimmungDetail,
  renderNudgeCount,
  renderNudgeList,
  renderMeasureDetail,
  renderMeasureDeps,
  renderGateAssociation,
  renderGateDetail,
  renderModelPosterior,
  renderPosteriorTable,
  renderBurndown,
  renderHealthSnapshot,
  renderResearchContext,
} from "./sections";

export const HAPAX_VIEW_TYPE = "hapax-context";

export class ContextPanel extends ItemView {
  private client: LogosClient;
  private currentContext: NoteContext | null = null;
  private onAction: (action: string) => Promise<void>;

  constructor(
    leaf: WorkspaceLeaf,
    client: LogosClient,
    onAction: (action: string) => Promise<void>,
  ) {
    super(leaf);
    this.client = client;
    this.onAction = onAction;
  }

  getViewType(): string {
    return HAPAX_VIEW_TYPE;
  }

  getDisplayText(): string {
    return "Hapax";
  }

  getIcon(): string {
    return "activity";
  }

  async onOpen(): Promise<void> {
    this.containerEl.addClass("hapax-panel");
    this.renderLoading();
    // Eager render with Unknown context so the panel shows data immediately
    // instead of waiting for a leaf change event (which may not fire on mobile).
    try {
      await this.render({
        kind: NoteKind.Unknown,
        tags: [],
      });
    } catch {
      // renderError handles display
    }
  }

  async onClose(): Promise<void> {
    // nothing to clean up
  }

  async update(ctx: NoteContext): Promise<void> {
    this.currentContext = ctx;
    await this.render(ctx);
  }

  async refresh(): Promise<void> {
    if (this.currentContext) {
      await this.render(this.currentContext);
    }
  }

  private renderLoading(): void {
    const content = this.containerEl.children[1] as HTMLElement;
    content.empty();
    content.createEl("p", { text: "Loading\u2026", cls: "hapax-loading" });
  }

  private renderError(err: unknown): void {
    const content = this.containerEl.children[1] as HTMLElement;
    content.empty();
    const msg = err instanceof Error ? err.message : String(err);
    content.createEl("p", {
      text: `Hapax error: ${msg}`,
      cls: "hapax-error",
    });
  }

  private async render(ctx: NoteContext): Promise<void> {
    try {
      const html = await this.buildHtml(ctx);
      const content = this.containerEl.children[1] as HTMLElement;
      content.empty();
      // All HTML is generated by our own section renderers using esc() for
      // user-supplied strings. External data is HTML-escaped before insertion.
      // nosec: controlled internal HTML, not untrusted user input.
      content.innerHTML = html; // nosec
      this.attachListeners(content);
    } catch (err) {
      this.renderError(err);
    }
  }

  private async buildHtml(ctx: NoteContext): Promise<string> {
    const parts: string[] = [];

    switch (ctx.kind) {
      case NoteKind.Measure: {
        const [measure, allMeasures, sprint] = await Promise.all([
          ctx.id
            ? this.client.getMeasure(ctx.id)
            : Promise.reject(new Error("No measure id")),
          this.client.getMeasures(),
          this.client.getSprint(),
        ]);
        parts.push(renderMeasureDetail(measure));
        parts.push(renderMeasureDeps(measure, allMeasures));
        if (measure.gate) {
          const gate = await this.client.getGate(measure.gate);
          parts.push(renderGateAssociation(gate));
        }
        const posterior = sprint.models[measure.model];
        if (posterior) {
          parts.push(renderModelPosterior(measure.model, posterior));
        }
        parts.push(renderSprintStatus(sprint));
        break;
      }

      case NoteKind.Gate: {
        const [gate, measures, sprint] = await Promise.all([
          ctx.id ? this.client.getGate(ctx.id) : Promise.reject(new Error("No gate id")),
          this.client.getMeasures(),
          this.client.getSprint(),
        ]);
        parts.push(renderGateDetail(gate, measures));
        parts.push(renderSprintStatus(sprint));
        break;
      }

      case NoteKind.SprintSummary: {
        const [sprint, stimmung, nudges] = await Promise.all([
          this.client.getSprint(),
          this.client.getStimmung(),
          this.client.getNudges(),
        ]);
        parts.push(renderBurndown(sprint));
        parts.push(renderStimmungBadge(stimmung));
        parts.push(renderNudgeCount(nudges));
        break;
      }

      case NoteKind.PosteriorTracker: {
        const sprint = await this.client.getSprint();
        parts.push(renderPosteriorTable(sprint.models));
        parts.push(renderSprintStatus(sprint));
        break;
      }

      case NoteKind.Research: {
        const [measures, sprint] = await Promise.all([
          this.client.getMeasures(),
          this.client.getSprint(),
        ]);
        parts.push(renderResearchContext(ctx, measures, sprint));
        if (ctx.model && sprint.models[ctx.model]) {
          parts.push(renderModelPosterior(ctx.model, sprint.models[ctx.model]));
        }
        parts.push(renderSprintStatus(sprint));
        break;
      }

      case NoteKind.Concept: {
        const [measures, sprint] = await Promise.all([
          this.client.getMeasures(),
          this.client.getSprint(),
        ]);
        parts.push(renderResearchContext(ctx, measures, sprint));
        parts.push(renderSprintStatus(sprint));
        break;
      }

      case NoteKind.Briefing: {
        const [health, stimmung, nudges, sprint] = await Promise.all([
          this.client.getHealth(),
          this.client.getStimmung(),
          this.client.getNudges(),
          this.client.getSprint(),
        ]);
        parts.push(renderHealthSnapshot(health));
        parts.push(renderStimmungDetail(stimmung));
        parts.push(renderNudgeCount(nudges));
        parts.push(renderSprintStatus(sprint));
        break;
      }

      case NoteKind.Nudges: {
        const [nudges, sprint] = await Promise.all([
          this.client.getNudges(),
          this.client.getSprint(),
        ]);
        parts.push(renderNudgeList(nudges));
        parts.push(renderSprintStatus(sprint));
        break;
      }

      case NoteKind.Goal: {
        const [gSprint, gStimmung, gNudges] = await Promise.all([
          this.client.getSprint(),
          this.client.getStimmung(),
          this.client.getNudges(),
        ]);
        parts.push(renderSprintStatus(gSprint));
        parts.push(renderStimmungBadge(gStimmung));
        parts.push(renderNudgeCount(gNudges));
        break;
      }

      case NoteKind.Daily: {
        const [dSprint, dStimmung, dNudges, dHealth] = await Promise.all([
          this.client.getSprint(),
          this.client.getStimmung(),
          this.client.getNudges(),
          this.client.getHealth(),
        ]);
        parts.push(renderHealthSnapshot(dHealth));
        parts.push(renderStimmungDetail(dStimmung));
        parts.push(renderSprintStatus(dSprint));
        parts.push(renderNudgeList(dNudges));
        break;
      }

      case NoteKind.Management: {
        const [mStimmung, mNudges] = await Promise.all([
          this.client.getStimmung(),
          this.client.getNudges(),
        ]);
        parts.push(renderStimmungBadge(mStimmung));
        parts.push(renderNudgeCount(mNudges));
        break;
      }

      case NoteKind.Studio: {
        const [sStimmung, sSprint] = await Promise.all([
          this.client.getStimmung(),
          this.client.getSprint(),
        ]);
        parts.push(renderStimmungDetail(sStimmung));
        parts.push(renderSprintStatus(sSprint));
        break;
      }

      case NoteKind.Unknown:
      default: {
        const [sprint, stimmung, nudges] = await Promise.all([
          this.client.getSprint(),
          this.client.getStimmung(),
          this.client.getNudges(),
        ]);
        parts.push(renderSprintStatus(sprint));
        parts.push(renderStimmungBadge(stimmung));
        parts.push(renderNudgeCount(nudges));
        break;
      }
    }

    return parts.join("\n");
  }

  private attachListeners(el: HTMLElement): void {
    el.querySelectorAll<HTMLButtonElement>("[data-action]").forEach((btn) => {
      btn.addEventListener("click", async (e) => {
        e.preventDefault();
        const action = btn.dataset["action"];
        if (action) {
          btn.disabled = true;
          try {
            await this.onAction(action);
            await this.refresh();
          } finally {
            btn.disabled = false;
          }
        }
      });
    });
  }
}
