"""Append-only event log writer.

The markdown log at
``~/Documents/Personal/20-projects/hapax-cc-tasks/_dashboard/cc-hygiene-events.md``
is the canonical audit trail. Sweeper appends one fenced YAML block per
sweep; the markdown wrapper exists so Obsidian renders the file
readably.

Invariant: this writer NEVER reads + rewrites the file. It only
appends. That keeps concurrent sweeps safe (worst case: two YAML
blocks at the same instant, both preserved).
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import datetime
from pathlib import Path

import yaml

from .models import HygieneEvent

DEFAULT_EVENT_LOG_PATH = (
    Path.home()
    / "Documents"
    / "Personal"
    / "20-projects"
    / "hapax-cc-tasks"
    / "_dashboard"
    / "cc-hygiene-events.md"
)
"""Canonical append-only event log."""

_HEADER_TEMPLATE = (
    "# cc-hygiene event log\n\n"
    "Append-only. Each sweep appends one fenced YAML block under a `## sweep` heading.\n"
    "Generated by `scripts/cc-hygiene-sweeper.py`. Do not hand-edit.\n\n"
)


def _ensure_header(path: Path) -> None:
    if path.exists() and path.stat().st_size > 0:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_HEADER_TEMPLATE, encoding="utf-8")


def append_events(
    events: Iterable[HygieneEvent],
    sweep_timestamp: datetime,
    path: Path = DEFAULT_EVENT_LOG_PATH,
    *,
    killswitch_active: bool = False,
) -> Path:
    """Append a sweep's events to the markdown log.

    Even if there are no events, append a heading + ``events: []`` block
    so the heartbeat is visible in the log.
    """
    _ensure_header(path)
    block_payload = {
        "sweep_timestamp": sweep_timestamp.isoformat(),
        "killswitch_active": killswitch_active,
        "events": [event.model_dump(mode="json") for event in events],
    }
    block = yaml.safe_dump(block_payload, sort_keys=False, allow_unicode=True)
    chunk = f"\n## sweep {sweep_timestamp.isoformat()}\n\n```yaml\n{block}```\n"
    with path.open("a", encoding="utf-8") as fh:
        fh.write(chunk)
    return path
