"""interview.py — Operator interview system for structured profile interrogation.

Drives a Socratic interview through the chat UI, accumulating facts and insights
that flush into the profiler pipeline on completion.

The interview agent is purpose-built for interrogation: it asks questions,
follows up, probes deeper, and challenges assumptions. Separate from the chat
agent to avoid diluting either role.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

_log = logging.getLogger(__name__)

from pydantic import BaseModel, Field
from pydantic_ai import Agent, RunContext

from shared.config import get_model
from shared.operator import get_goals, get_patterns, get_system_prompt_fragment

# Import Langfuse OTel config (side-effect: configures exporter)
try:
    from shared import langfuse_config  # noqa: F401
except ImportError:
    pass


# ── Data models ──────────────────────────────────────────────────────────────


class InterviewTopic(BaseModel):
    """A topic to explore during the interview."""

    dimension: str = Field(description="Profile dimension (identity, workflow, philosophy, etc.)")
    topic: str = Field(description="Specific topic within dimension")
    rationale: str = Field(description="Why this topic needs exploration")
    question_seed: str = Field(description="Opening question")
    depth: Literal["surface", "deep", "challenge"] = Field(
        description="surface=new area, deep=elaborate existing, challenge=critique"
    )


class InterviewPlan(BaseModel):
    """The full interview plan generated by LLM analysis."""

    topics: list[InterviewTopic]
    overall_focus: str = Field(description="1-2 sentence description of interview direction")


class RecordedFact(BaseModel):
    """A fact captured during the interview."""

    dimension: str
    key: str
    value: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence: str = Field(description="What the operator said that supports this")


class RecordedInsight(BaseModel):
    """A higher-level insight from the interview."""

    category: Literal[
        "workflow_gap",
        "goal_refinement",
        "practice_critique",
        "aspiration",
        "contradiction",
        "neurocognitive_pattern",
    ]
    description: str
    recommendation: str = Field(description="Concrete suggestion if applicable")


class InterviewState(BaseModel):
    """Persistent state for an in-progress interview."""

    plan: InterviewPlan
    facts: list[RecordedFact] = Field(default_factory=list)
    insights: list[RecordedInsight] = Field(default_factory=list)
    topics_explored: list[str] = Field(default_factory=list)
    started_at: str = ""

    @property
    def all_topics_explored(self) -> bool:
        """True when every topic in the plan has been explored."""
        return len(self.plan.topics) > 0 and all(
            t.topic in self.topics_explored for t in self.plan.topics
        )

    @property
    def current_topic(self) -> InterviewTopic | None:
        """The next unexplored topic, or None if all done."""
        for t in self.plan.topics:
            if t.topic not in self.topics_explored:
                return t
        return None


# ── Profile analysis (deterministic, no LLM) ────────────────────────────────


@dataclass
class ProfileAnalysis:
    """Results of deterministic profile gap analysis."""

    sparse_dimensions: list[dict[str, Any]] = field(default_factory=list)
    missing_dimensions: list[str] = field(default_factory=list)
    low_confidence_clusters: list[dict[str, Any]] = field(default_factory=list)
    goal_gaps: list[dict[str, Any]] = field(default_factory=list)
    total_facts: int = 0
    dimension_stats: dict[str, dict[str, Any]] = field(default_factory=dict)
    neurocognitive_gap: bool = False


def analyze_profile() -> ProfileAnalysis:
    """Analyze the current profile to identify gaps, sparse areas, and topics to explore.

    Reads profiles/operator-profile.json and operator.json. Pure deterministic — no LLM calls.
    """
    from agents.profiler import (
        group_facts_by_dimension,
        load_existing_profile,
    )
    from shared.dimensions import get_dimension_names

    analysis = ProfileAnalysis()
    profile = load_existing_profile()

    if profile is None:
        analysis.missing_dimensions = list(get_dimension_names())
        return analysis

    # Collect all facts
    all_facts = [f for dim in profile.dimensions for f in dim.facts]
    analysis.total_facts = len(all_facts)
    grouped = group_facts_by_dimension(all_facts)

    # Analyze each dimension
    for dim_name in get_dimension_names():
        facts = grouped.get(dim_name, [])
        count = len(facts)
        avg_conf = sum(f.confidence for f in facts) / count if count else 0.0

        analysis.dimension_stats[dim_name] = {
            "count": count,
            "avg_confidence": round(avg_conf, 2),
        }

        if count == 0:
            analysis.missing_dimensions.append(dim_name)
        elif count < 3:
            analysis.sparse_dimensions.append(
                {
                    "dimension": dim_name,
                    "fact_count": count,
                    "avg_confidence": round(avg_conf, 2),
                }
            )

        # Low-confidence clusters
        low_conf = [f for f in facts if f.confidence < 0.7]
        if len(low_conf) >= 2:
            analysis.low_confidence_clusters.append(
                {
                    "dimension": dim_name,
                    "count": len(low_conf),
                    "keys": [f.key for f in low_conf],
                }
            )

    # Goal gaps — goals with no corresponding high-confidence facts
    try:
        goals = get_goals()
        for goal in goals:
            goal_id = goal.get("id", "")
            goal_name = goal.get("name", "")
            # Check if any facts reference this goal area
            has_facts = any(
                goal_id in f.key or goal_name.lower() in f.value.lower()
                for f in all_facts
                if f.confidence >= 0.7
            )
            if not has_facts:
                analysis.goal_gaps.append(
                    {
                        "goal_id": goal_id,
                        "goal_name": goal_name,
                        "status": goal.get("status", "unknown"),
                    }
                )
    except Exception:
        _log.debug("Could not read operator goals", exc_info=True)

    # Neurocognitive gap — check if dimension is sparse AND operator.json section empty
    neuro_stats = analysis.dimension_stats.get("neurocognitive_profile", {"count": 0})
    if neuro_stats.get("count", 0) < 5:
        try:
            from shared.operator import get_neurocognitive_profile

            neuro_data = get_neurocognitive_profile()
            total_findings = sum(len(v) for v in neuro_data.values()) if neuro_data else 0
            if total_findings < 3:
                analysis.neurocognitive_gap = True
        except Exception:
            _log.debug("Could not read neurocognitive profile", exc_info=True)
            analysis.neurocognitive_gap = True

    return analysis


# ── Interview plan generation (LLM) ─────────────────────────────────────────

PLAN_SYSTEM_PROMPT = """\
You are an interview planner. Given a profile gap analysis, system context, and current
profile summary, generate a structured interview plan.

CRITICAL — Respect Existing Coverage:
- Dimensions listed as "well-covered" have extensive, high-confidence facts already.
  Do NOT generate deep exploration topics for these. At most, include ONE "challenge"
  topic per well-covered dimension — never surface or deep exploration.
- Focus your plan on genuine gaps: missing dimensions, sparse dimensions, low-confidence
  clusters, and goal areas without corresponding facts.
- A dimension with 20+ facts at 0.8+ confidence is WELL ESTABLISHED. The operator has
  already been thoroughly interviewed on it. Generating multiple topics for it wastes
  their time and makes the interview feel regressive.

CRITICAL — System Context Awareness:
- You will receive a description of the system this interview runs inside.
- Do NOT generate topics asking the operator to describe infrastructure that is documented
  in the system context. The system IS the answer to many goals — the interviewer already
  knows about it.
- For goals that the system clearly addresses (e.g., "LLM-first environment" when the
  system IS an LLM-first environment), do NOT ask "what does this look like." Instead,
  generate topics about: operator satisfaction, what's missing, what's next, friction
  points, or how the system changed their workflow.

CRITICAL — Topic Count:
- Generate fewer topics when the profile is well-covered. A profile with 2000+ facts
  across 13 dimensions needs refinement, not breadth.
- Well-covered profile (most dimensions >20 facts): generate 5-8 topics max.
- Mixed coverage: generate 8-12 topics.
- Sparse profile (<500 total facts): generate 10-15 topics.

Prioritize:
1. Missing and sparse dimensions (new information needed)
2. Low-confidence facts (clarification needed)
3. Goals and aspirations — but only what ISN'T already evident from the system context
4. Methodology critique (challenge existing practices constructively)

Each topic should have:
- A clear rationale for why it needs exploration
- An opening question that invites reflection, not yes/no answers
- An appropriate depth: "surface" for new areas, "deep" to elaborate on existing facts,
  "challenge" to constructively critique practices or goals
"""

# Neurocognitive exploration guidance — only injected when there's an actual gap
NEURO_EXPLORATION_GUIDANCE = """\

Additionally, the neurocognitive profile is sparse or missing. Explore cognitive patterns
through open-ended discovery. Research areas to guide (NOT assume):
- Task initiation: What blocks starting? What unblocks?
- Task persistence: Hyperfocus triggers, disengagement, transitions
- Time perception: Where time blindness hits, what external cues work
- Decision making: Paralysis triggers, effective heuristics
- Sensory environment: Focus supports, overwhelm triggers
- Energy cycles: Daily/weekly patterns, depletion indicators, recovery
- Motivation: Interest triggers, sustainable vs depleting motivators
- Demand sensitivity: What feels like a demand, effective framing

CRITICAL: These guide exploration, not diagnosis. Discover specific patterns —
some areas may not apply, others may reveal unexpected patterns. Ask about
experience and situations, never about conditions. Use dimension
"neurocognitive_profile" and depth "deep" for these topics.
"""


WELL_COVERED_THRESHOLD_FACTS = 20
WELL_COVERED_THRESHOLD_CONFIDENCE = 0.8


async def generate_interview_plan(
    analysis: ProfileAnalysis,
    *,
    model_alias: str = "balanced",
) -> InterviewPlan:
    """Generate an interview plan from profile analysis using LLM.

    Uses the pre-computed digest for dimension summaries when available,
    falling back to raw stats when the digest doesn't exist.
    """
    # Classify dimensions into well-covered vs needs-work
    well_covered: list[str] = []
    for dim, stats in analysis.dimension_stats.items():
        if (
            stats["count"] >= WELL_COVERED_THRESHOLD_FACTS
            and stats["avg_confidence"] >= WELL_COVERED_THRESHOLD_CONFIDENCE
        ):
            well_covered.append(
                f"  - {dim}: {stats['count']} facts, avg confidence {stats['avg_confidence']} [WELL-COVERED]"
            )

    # Try to load digest for richer planner input
    digest = None
    try:
        from shared.profile_store import ProfileStore

        digest = ProfileStore().get_digest()
    except Exception:
        pass

    # Build analysis summary for the planner
    parts: list[str] = []

    # Use digest overall summary if available, fall back to profile summary
    if digest and digest.get("overall_summary"):
        parts.append(f"Profile: {digest['overall_summary']}")
    else:
        from agents.profiler import load_existing_profile

        profile = load_existing_profile()
        if profile and profile.summary:
            parts.append(f"Profile: {profile.summary}")

    parts.append(f"\nTotal profile facts: {analysis.total_facts}")

    # Dimension coverage — use digest summaries when available
    parts.append("\nDimension coverage:")
    for dim, stats in sorted(analysis.dimension_stats.items()):
        marker = (
            " [WELL-COVERED]"
            if (
                stats["count"] >= WELL_COVERED_THRESHOLD_FACTS
                and stats["avg_confidence"] >= WELL_COVERED_THRESHOLD_CONFIDENCE
            )
            else ""
        )
        parts.append(
            f"  - {dim}: {stats['count']} facts, avg confidence {stats['avg_confidence']}{marker}"
        )

    if analysis.missing_dimensions:
        parts.append(
            f"\nMissing dimensions (no facts — PRIORITIZE these): {', '.join(analysis.missing_dimensions)}"
        )

    if analysis.sparse_dimensions:
        parts.append("\nSparse dimensions (PRIORITIZE these):")
        for s in analysis.sparse_dimensions:
            parts.append(
                f"  - {s['dimension']}: {s['fact_count']} facts, avg confidence {s['avg_confidence']}"
            )

    if analysis.low_confidence_clusters:
        parts.append("\nLow-confidence clusters (need clarification):")
        for c in analysis.low_confidence_clusters:
            parts.append(
                f"  - {c['dimension']}: {c['count']} facts below 0.7 ({', '.join(c['keys'])})"
            )

    if analysis.goal_gaps:
        parts.append("\nGoals without corresponding profile facts:")
        for g in analysis.goal_gaps:
            parts.append(f"  - {g['goal_name']} ({g['goal_id']}, status: {g['status']})")

    # Conditionally inject neurocognitive exploration guidance
    system_prompt = PLAN_SYSTEM_PROMPT
    if analysis.neurocognitive_gap:
        system_prompt += NEURO_EXPLORATION_GUIDANCE

    planner = Agent(
        get_model(model_alias),
        output_type=InterviewPlan,
        system_prompt=system_prompt,
    )

    result = await planner.run("\n".join(parts))
    plan = result.output

    # Programmatic enforcement: strip topics for well-covered dimensions.
    # The LLM planner may still generate them despite instructions — this is the safety net.
    well_covered_dims = {
        dim
        for dim, stats in analysis.dimension_stats.items()
        if stats["count"] >= WELL_COVERED_THRESHOLD_FACTS
        and stats["avg_confidence"] >= WELL_COVERED_THRESHOLD_CONFIDENCE
    }
    if well_covered_dims:
        filtered: list[InterviewTopic] = []
        challenge_used: set[str] = set()
        for topic in plan.topics:
            if topic.dimension in well_covered_dims:
                # Allow at most 1 challenge topic per well-covered dimension
                if topic.depth == "challenge" and topic.dimension not in challenge_used:
                    challenge_used.add(topic.dimension)
                    filtered.append(topic)
                # else: silently drop surface/deep topics for well-covered dims
            else:
                filtered.append(topic)
        plan.topics = filtered

    return plan


# ── Interview agent ──────────────────────────────────────────────────────────

INTERVIEW_SYSTEM_PROMPT = """\
You are conducting a structured operator profile interview. You are Socratic — you \
ask, probe, and challenge. The operator answers.

Rules (follow ALL of these exactly):

1. ONE QUESTION PER TURN. Never ask two questions in one message. Pick the single \
most important question and ask it clearly.

2. Use your context tools to look up constraints, patterns, and profile facts before \
asking questions. NEVER ask the operator to describe things you can look up. Instead, \
reference what you know and ask about gaps, friction, or what's changed.

3. After each operator answer: record facts/insights with tools, then either follow \
up (max 2-3 exchanges per topic) or call mark_topic_explored and move to the next topic. \
A thorough single answer can complete a topic — don't pad with unnecessary follow-ups.

4. Never re-ask something the operator answered earlier in this conversation or in a \
prior interview. Use get_profile_summary and search_profile to check existing coverage.

5. For neurocognitive topics, ask about situations and experiences, never conditions. \
Frame patterns as system design inputs ("how should the system work for you") not pathology.

6. Explain briefly why you're asking (1 sentence of context), then ask the question.
"""


@dataclass
class InterviewDeps:
    """Runtime dependencies for the interview agent."""

    state: InterviewState
    project_dir: Path
    conversation_summary: str = ""


def create_interview_agent(model_alias: str = "balanced") -> Agent[InterviewDeps, str]:
    """Create the interview agent with tools for recording facts and managing the interview."""

    operator_context = get_system_prompt_fragment("logos-chat")

    agent = Agent(
        get_model(model_alias),
        deps_type=InterviewDeps,
        system_prompt=operator_context + INTERVIEW_SYSTEM_PROMPT,
    )

    # Register on-demand operator context tools
    from shared.context_tools import get_context_tools

    for tool_fn in get_context_tools():
        agent.tool(tool_fn)

    # Dynamic context injection — current plan and progress
    @agent.system_prompt
    async def inject_interview_context(ctx: RunContext[InterviewDeps]) -> str:
        state = ctx.deps.state
        plan = state.plan

        parts: list[str] = []
        parts.append(f"Interview focus: {plan.overall_focus}")
        parts.append(f"Progress: {len(state.topics_explored)}/{len(plan.topics)} topics explored")
        parts.append(
            f"Facts recorded: {len(state.facts)}, Insights recorded: {len(state.insights)}"
        )

        # Current topic
        remaining = [t for t in plan.topics if t.topic not in state.topics_explored]
        if remaining:
            current = remaining[0]
            parts.append(
                f"\nCurrent topic: {current.topic} ({current.dimension}, depth: {current.depth})"
            )
            parts.append(f"Rationale: {current.rationale}")
            parts.append(f"Opening question: {current.question_seed}")

        # Upcoming topics
        if len(remaining) > 1:
            parts.append(f"\nUpcoming topics: {', '.join(t.topic for t in remaining[1:4])}")

        # Conversation summary from compacted history — prevents re-asking
        if ctx.deps.conversation_summary:
            parts.append(
                f"\nEarlier conversation summary (review before asking questions):\n{ctx.deps.conversation_summary}"
            )

        # Already-recorded facts — so the LLM knows what it's captured
        if state.facts:
            fact_lines = [f"- [{f.dimension}] {f.key}: {f.value}" for f in state.facts[-15:]]
            parts.append("\nFacts already recorded:\n" + "\n".join(fact_lines))

        return "\n".join(parts)

    # ── Tools ────────────────────────────────────────────────────────────

    @agent.tool
    async def read_profile_dimension(ctx: RunContext[InterviewDeps], dimension: str) -> str:
        """Read current facts for a profile dimension to inform follow-up questions.

        Args:
            dimension: Profile dimension name (e.g. 'work_patterns', 'values').
        """
        from agents.profiler import load_existing_profile

        profile = load_existing_profile()
        if not profile:
            return f"No profile found. Dimension '{dimension}' has no data."

        for dim in profile.dimensions:
            if dim.name == dimension:
                if not dim.facts:
                    return f"Dimension '{dimension}' exists but has no facts."
                lines = [f"## {dimension} ({len(dim.facts)} facts)"]
                if dim.summary:
                    lines.append(dim.summary)
                    lines.append("")
                for f in dim.facts:
                    lines.append(f"- **{f.key}**: {f.value} (confidence: {f.confidence})")
                return "\n".join(lines)

        return f"Dimension '{dimension}' not found in profile."

    @agent.tool
    async def record_fact(
        ctx: RunContext[InterviewDeps],
        dimension: str,
        key: str,
        value: str,
        confidence: float,
        evidence: str,
    ) -> str:
        """Record a fact extracted from the operator's answer.

        Args:
            dimension: Profile dimension (identity, workflow, philosophy, etc.).
            key: Snake_case identifier for this fact.
            value: The factual information.
            confidence: Confidence 0.0-1.0 based on how explicit the statement was.
            evidence: What the operator said that supports this fact.
        """
        fact = RecordedFact(
            dimension=dimension,
            key=key,
            value=value,
            confidence=min(max(confidence, 0.0), 1.0),
            evidence=evidence,
        )
        ctx.deps.state.facts.append(fact)
        return f"Recorded fact: [{dimension}] {key} = {value} (confidence: {confidence})"

    @agent.tool
    async def record_insight(
        ctx: RunContext[InterviewDeps],
        category: str,
        description: str,
        recommendation: str,
    ) -> str:
        """Record a higher-level insight or critique from the interview.

        Args:
            category: One of: workflow_gap, goal_refinement, practice_critique, aspiration, contradiction.
            description: What was observed or identified.
            recommendation: Concrete suggestion if applicable.
        """
        valid_categories = (
            "workflow_gap",
            "goal_refinement",
            "practice_critique",
            "aspiration",
            "contradiction",
            "neurocognitive_pattern",
        )
        if category not in valid_categories:
            return f"Invalid category '{category}'. Must be one of: {', '.join(valid_categories)}"
        insight = RecordedInsight(
            category=category,  # type: ignore[arg-type]
            description=description,
            recommendation=recommendation,
        )
        ctx.deps.state.insights.append(insight)
        return f"Recorded insight: [{category}] {description}"

    @agent.tool
    async def mark_topic_explored(ctx: RunContext[InterviewDeps], topic: str) -> str:
        """Mark a topic as sufficiently covered and move to the next.

        Args:
            topic: The topic string to mark as explored.
        """
        if topic not in ctx.deps.state.topics_explored:
            ctx.deps.state.topics_explored.append(topic)

        remaining = [
            t for t in ctx.deps.state.plan.topics if t.topic not in ctx.deps.state.topics_explored
        ]

        if remaining:
            next_topic = remaining[0]
            return (
                f"Topic '{topic}' marked complete. "
                f"{len(remaining)} topics remaining. "
                f"Next: {next_topic.topic} ({next_topic.dimension}, {next_topic.depth})"
            )
        return f"Topic '{topic}' marked complete. All topics explored!"

    @agent.tool
    async def get_interview_progress(ctx: RunContext[InterviewDeps]) -> str:
        """Get current interview progress summary."""
        state = ctx.deps.state
        total = len(state.plan.topics)
        explored = len(state.topics_explored)
        facts = len(state.facts)
        insights = len(state.insights)

        lines = [
            f"Topics: {explored}/{total} explored",
            f"Facts recorded: {facts}",
            f"Insights recorded: {insights}",
        ]

        if state.topics_explored:
            lines.append(f"Explored: {', '.join(state.topics_explored)}")

        remaining = [t.topic for t in state.plan.topics if t.topic not in state.topics_explored]
        if remaining:
            lines.append(f"Remaining: {', '.join(remaining)}")

        return "\n".join(lines)

    @agent.tool
    async def read_goals(ctx: RunContext[InterviewDeps]) -> str:
        """Read operator goals from operator.json."""
        try:
            goals = get_goals()
            if not goals:
                return "No goals found in operator.json."
            lines = []
            for g in goals:
                status = g.get("status", "unknown")
                progress = g.get("progress", "")
                lines.append(f"- **{g.get('name', '?')}** ({g.get('id', '?')}, {status})")
                if g.get("description"):
                    lines.append(f"  {g['description']}")
                if progress:
                    lines.append(f"  Progress: {progress}")
            return "\n".join(lines)
        except Exception as e:
            return f"Error reading goals: {e}"

    @agent.tool
    async def read_patterns(ctx: RunContext[InterviewDeps]) -> str:
        """Read operator behavioral patterns from operator.json."""
        try:
            patterns = get_patterns()
            if not patterns:
                return "No patterns found in operator.json."
            return "\n".join(f"- {p}" for p in patterns)
        except Exception as e:
            return f"Error reading patterns: {e}"

    return agent


# ── Profiler integration ─────────────────────────────────────────────────────


def format_interview_summary(state: InterviewState) -> str:
    """Format a human-readable summary of interview results."""
    lines: list[str] = []
    lines.append(
        f"Interview complete: {len(state.topics_explored)}/{len(state.plan.topics)} topics explored"
    )
    lines.append(f"Facts recorded: {len(state.facts)}")
    lines.append(f"Insights recorded: {len(state.insights)}")

    if state.facts:
        lines.append("\nFacts by dimension:")
        by_dim: dict[str, list[RecordedFact]] = {}
        for f in state.facts:
            by_dim.setdefault(f.dimension, []).append(f)
        for dim, facts in sorted(by_dim.items()):
            lines.append(f"  {dim}: {len(facts)}")
            for f in facts:
                lines.append(f"    - {f.key}: {f.value}")

    if state.insights:
        lines.append("\nInsights:")
        for i in state.insights:
            lines.append(f"  [{i.category}] {i.description}")
            if i.recommendation:
                lines.append(f"    Recommendation: {i.recommendation}")

    return "\n".join(lines)


# ── Pending fact flush ────────────────────────────────────────────────────


def flush_pending_facts() -> str:
    """Read pending JSONL facts and flush to profile pipeline."""
    import json
    import os
    import tempfile

    from agents.profiler import flush_interview_facts
    from shared.config import LOGOS_STATE_DIR

    facts_path = LOGOS_STATE_DIR / "pending-facts.jsonl"
    if not facts_path.exists():
        return "no pending facts to flush."

    lines = facts_path.read_text().strip().splitlines()
    if not lines:
        return "no pending facts to flush."

    facts = []
    for line in lines:
        try:
            entry = json.loads(line)
            facts.append(
                RecordedFact(
                    dimension=entry["dimension"],
                    key=entry["key"],
                    value=entry["value"],
                    confidence=entry.get("confidence", 0.6),
                    evidence=entry.get("evidence", ""),
                )
            )
        except (json.JSONDecodeError, KeyError):
            continue

    if not facts:
        return "no valid facts found."

    result = flush_interview_facts(facts=facts, insights=[], source="conversation:logos")
    # Clear the pending file after successful flush (atomic write)
    tmp_fd, tmp_path = tempfile.mkstemp(dir=str(facts_path.parent), suffix=".tmp")
    try:
        os.close(tmp_fd)  # Just need an empty file
        os.replace(tmp_path, str(facts_path))
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
    return f"Flushed {len(facts)} facts. {result}"
