#!/usr/bin/env -S uv run --script
"""Emit ``docs/aesthetic-library/cdn-index.md`` — a SHA-pinned URL
catalog of every redistributable asset in the aesthetic library.

AUDIT-21 acceptance: ≥1 new consumer outside OMG of the
``shared.aesthetic_library.web_export.build_web_url`` primitive.

Walks ``library().manifest_entries()`` and emits a deterministic
markdown table of (source group, asset name, kind, license,
SHA-pinned URL). Output is byte-stable across runs for a fixed
manifest because the URL builder hashes are SHA-pinned and the
walker iterates in manifest order.

Usage::

    python scripts/generate-aesthetic-library-cdn-index.py
    # → writes docs/aesthetic-library/cdn-index.md

    python scripts/generate-aesthetic-library-cdn-index.py --check
    # → exits 1 if cdn-index.md is stale relative to current manifest

The ``--check`` mode is suitable for CI: a manifest update without a
corresponding cdn-index regeneration is treated as drift.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from shared.aesthetic_library import library
from shared.aesthetic_library.web_export import build_web_url

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "aesthetic-library" / "cdn-index.md"

INDEX_HEADER = """\
# Aesthetic library — CDN URL index

Auto-generated by ``scripts/generate-aesthetic-library-cdn-index.py``.

Every redistributable asset in ``assets/aesthetic-library/`` listed
with its SHA-pinned CDN URL. The URL is byte-stable for a given
manifest snapshot; an asset bytes change → manifest SHA change → URL
query-string flip → cached references invalidate cleanly.

| Source | Asset | Kind | License | URL |
|---|---|---|---|---|
"""


def render_index() -> str:
    """Render the markdown index from the live manifest."""
    lib = library()
    rows: list[str] = []
    for entry in sorted(lib.manifest_entries(), key=lambda e: (e.source, e.name)):
        # ``ManifestEntry.path`` is a relative POSIX-style string; pass
        # via ``Path`` so ``build_web_url`` handles separators uniformly.
        url = build_web_url(lib.root, lib.root / entry.path, entry.sha256)
        rows.append(
            f"| {entry.source} | `{entry.name}` | {entry.kind} | {entry.license} | "
            f"[{entry.sha256[:8]}…]({url}) |"
        )
    return INDEX_HEADER + "\n".join(rows) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Path to write the index (default: %(default)s)",
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if output is stale relative to current manifest",
    )
    args = p.parse_args(argv)

    rendered = render_index()

    if args.check:
        if not args.output.exists():
            print(f"cdn-index missing: {args.output}", file=sys.stderr)
            return 1
        existing = args.output.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                f"cdn-index stale: regenerate with "
                f"`python {Path(__file__).relative_to(REPO_ROOT)}`",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
