context.modules = [
    {
        name = libpipewire-module-echo-cancel
        args = {
            capture.props = {
                node.name = "echo_cancel_capture"
                node.description = "Echo Cancel Capture"
            }
            source.props = {
                node.name = "echo_cancel_source"
                node.description = "Echo Cancel Source"
            }
            playback.props = {
                node.name = "echo_cancel_playback"
                node.description = "Echo Cancel Playback"
            }
            sink.props = {
                node.name = "echo_cancel_sink"
                node.description = "Echo Cancel Sink"
            }
            library.name = aec/libspa-aec-webrtc
            aec.args = {
                webrtc.gain_controller = true
                webrtc.noise_suppression = true
                webrtc.extended_filter = true
            }
        }
    }
]
